name: Android CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '10 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
