name: Android CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '10 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build the app
        run: ./gradlew test
